# Generated by Django 5.2.4 on 2025-07-07 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tadbir nomi')),
                ('description', models.TextField(verbose_name='Tadbir haqida')),
                ('category', models.CharField(choices=[('educational', "Ta'limiy"), ('cultural', 'Madaniy'), ('sports', 'Sport'), ('social', 'Ijtimoiy'), ('other', 'Boshqa')], max_length=20, verbose_name='Kategoriya')),
                ('event_date', models.DateTimeField(verbose_name='Tadbir sanasi')),
                ('location', models.CharField(max_length=200, verbose_name="O'tkazilgan joy")),
                ('participants_count', models.PositiveIntegerField(verbose_name='Ishtirokchilar soni')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan sana")),
                ('dean_comment', models.TextField(blank=True, verbose_name='Dekan izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Tashkilotchi (Tutor)')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiquvchi")),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='event_photos/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Rasm izohi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event', verbose_name='Tadbir')),
            ],
            options={
                'verbose_name': 'Tadbir rasmi',
                'verbose_name_plural': 'Tadbir rasmlari',
            },
        ),
    ]
