# Generated by Django 3.1 on 2025-07-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Davlat')),
            ],
            options={
                'verbose_name': 'Davlat',
                'verbose_name_plural': 'Davlatlar',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
            },
        ),
        migrations.CreateModel(
            name='Mutaxassislik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mutaxassislik nomi')),
            ],
            options={
                'verbose_name': 'Mutaxassislik',
                'verbose_name_plural': 'Mutaxassisliklar',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name="To'liq manzil")),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='Xona raqami')),
                ('room_type', models.CharField(choices=[('single', 'Yakka xona'), ('double', 'Ikki kishilik'), ('shared', 'Umumiy xona')], max_length=10, verbose_name='Xona turi')),
                ('area', models.FloatField(help_text='Kvadrat metrda', verbose_name='Maydoni')),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ijara narxi')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='Oshxona bor')),
                ('has_bathroom', models.BooleanField(default=False, verbose_name='Hammom bor')),
                ('has_internet', models.BooleanField(default=False, verbose_name='Internet bor')),
                ('has_heating', models.BooleanField(default=False, verbose_name='Isitish tizimi')),
                ('condition', models.CharField(choices=[('excellent', "A'lo"), ('good', 'Yaxshi'), ('average', "O'rtacha"), ('poor', 'Yomon')], default='good', max_length=10, verbose_name='Umumiy holati')),
                ('landlord_name', models.CharField(max_length=100, verbose_name='Uy egasi ismi')),
                ('landlord_phone', models.CharField(max_length=20, verbose_name='Uy egasi telefoni')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.district', verbose_name='Tuman')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Ijara xona',
                'verbose_name_plural': 'Ijara xonalar',
            },
        ),
        migrations.CreateModel(
            name='TTJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='TTJ nomi')),
                ('address', models.TextField(verbose_name="To'liq manzil")),
                ('capacity', models.PositiveIntegerField(verbose_name="Sig'imi (kishi)")),
                ('has_internet', models.BooleanField(default=False, verbose_name='Internet bor')),
                ('has_heating', models.BooleanField(default=False, verbose_name='Isitish tizimi')),
                ('condition', models.CharField(choices=[('excellent', "A'lo"), ('good', 'Yaxshi'), ('average', "O'rtacha"), ('poor', 'Yomon')], default='good', max_length=10, verbose_name='Umumiy holati')),
                ('manager_name', models.CharField(max_length=100, verbose_name='TTJ boshqaruvchisi ismi')),
                ('manager_phone', models.CharField(max_length=20, verbose_name='TTJ boshqaruvchisi telefoni')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.district', verbose_name='Tuman')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Talabalar turar joyi (TTJ)',
                'verbose_name_plural': 'Talabalar turar joylari (TTJ)',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Otasining ismi')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('is_renting', models.BooleanField(default=False, verbose_name='Ijara xonadonida yashaydi')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('is_orphan', models.BooleanField(default=False, verbose_name='Yetim')),
                ('has_disability', models.BooleanField(default=False, verbose_name='Nogironligi bor')),
                ('lives_in_dormitory', models.BooleanField(default=False, verbose_name='TTJ da yashaydi')),
                ('student_id', models.IntegerField(default=0, unique=True, verbose_name='Talaba ID')),
                ('fuqaro', models.CharField(choices=[('uz', 'O‘zbekiston fuqarosi'), ('foreign', 'Chet el fuqarosi')], default='uz', max_length=20, verbose_name='Fuqarolik')),
                ('jshshir', models.CharField(max_length=14, unique=True, verbose_name='JSHSHIR raqami')),
                ('passport', models.CharField(max_length=20, unique=True, verbose_name='Pasport raqami')),
                ('otm', models.CharField(max_length=100, verbose_name="Oliy ta'lim muassasasi")),
                ('talim_turi', models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistr', 'Magistr'), ('doktorant', 'Doktorant'), ('phd', 'PhD')], default='bakalavr', max_length=20, verbose_name="Ta'lim turi")),
                ('tulov_turi', models.CharField(choices=[('grant', 'Davlat granti'), ('contract', 'To‘lov-kontrakt')], default='grant', max_length=20, verbose_name="To'lov turi")),
                ('talim_shakli', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('kechki', 'Kechki'), ('masofaviy', 'Masofaviy')], default='kunduzgi', max_length=20, verbose_name="Ta'lim shakli")),
                ('shifr', models.CharField(max_length=20, verbose_name='Shifr')),
                ('temporary_address', models.TextField(blank=True, verbose_name='Yashash manzili')),
                ('appartment_type', models.CharField(choices=[('ttj', 'TTJ (Talabalar turar joyi)'), ('rent', 'Ijara xonadon'), ('home', 'Uyda yashaydi')], default='ttj', max_length=20, verbose_name='Yashash turi')),
                ('family_type', models.CharField(choices=[('turmush_qurgan', 'Turmush qurgan'), ('turmush_qurmagan', 'Turmush qurgan emas')], default='turmush_qurmagan', max_length=20, verbose_name='Oilaviy holati')),
                ('const_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='const_students', to='students.district', verbose_name='Doimiy tuman')),
                ('const_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='const_students', to='students.region', verbose_name='Doimiy viloyat')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.country', verbose_name='Vatan')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='faculty.group', verbose_name='Guruh')),
                ('mutaxassislik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.mutaxassislik', verbose_name='Mutaxassislik')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.room', verbose_name='Ijara xona')),
                ('temporary_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_students', to='students.district', verbose_name='Vaqtincha tuman')),
                ('temporary_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_students', to='students.region', verbose_name='Vaqtincha viloyat')),
                ('ttj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.ttj', verbose_name='TTJ')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.region', verbose_name='Viloyat'),
        ),
    ]
