# Generated by Django 5.2.4 on 2025-07-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_room_alter_country_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bully_student',
            field=models.BooleanField(default=False, verbose_name='Bezori talaba'),
        ),
    ]
