# Generated by Django 5.2.4 on 2025-07-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_bully_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_in_orphanage',
            field=models.BooleanField(default=False, verbose_name='Mehribonlik uyi tarbiyalanuvchisi'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_in_social_protection',
            field=models.BooleanField(default=False, verbose_name='Ijtimoiy himoya reestiriga kiritilgan'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_in_temir_daftar',
            field=models.BooleanField(default=False, verbose_name='Temir daftarga kiritilgan oila farzandi'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_in_women_daftar',
            field=models.BooleanField(default=False, verbose_name="Ayollar daftari ro'yxatiga kiritilgan"),
        ),
        migrations.AddField(
            model_name='student',
            name='is_in_youth_daftar',
            field=models.BooleanField(default=False, verbose_name="Yoshlar daftari ro'yxatiga kiritilgan"),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasi yoki Onasi vafot etgan'),
        ),
        migrations.AddField(
            model_name='student',
            name='parents_divorced',
            field=models.BooleanField(default=False, verbose_name='Ota-onasi ajrashgan'),
        ),
    ]
