# Generated by Django 5.2.4 on 2025-07-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shifr',
            field=models.CharField(blank=True, max_length=20, verbose_name='Shifr'),
        ),
    ]
