# Generated by Django 3.1 on 2025-07-04 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rtacha"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='medium', max_length=10, verbose_name='Muhimlik darajasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=15, verbose_name='Holat')),
                ('due_date', models.DateTimeField(verbose_name='Bajarish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan sana')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Reja',
                'verbose_name_plural': 'Rejalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Eslatma sarlavhasi')),
                ('message', models.TextField(verbose_name='Eslatma matni')),
                ('remind_at', models.DateTimeField(verbose_name='Eslatish vaqti')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Yuborilganmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='plans.plan', verbose_name='Reja')),
            ],
            options={
                'verbose_name': 'Eslatma',
                'verbose_name_plural': 'Eslatmalar',
                'ordering': ['remind_at'],
            },
        ),
    ]
