# Generated by Django 5.2.4 on 2025-09-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('faculty', '0002_alter_faculty_id_alter_group_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.CharField(choices=[('1', '1st Period (8:30 - 9:50)'), ('2', '2nd Period (10:00 - 11:20)'), ('3', '3rd Period (11:30 - 12:50)')], default='Asia/Tashkent', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('group', 'date', 'period')},
        ),
    ]
